services:
  claude-coder:
    build:
      context: .
      dockerfile: Dockerfile
    image: claude-coder-dev
    container_name: claude-coder
    volumes:
      - $HOME/.claude-docker:/home/developer/.claude
      - $HOME/.claude-docker.json:/home/developer/.claude.json
      - ${PROJECT_DIR:-/tmp/empty}:/home/developer/projects/code
    environment:
      - PROJECT_DIR
    stdin_open: true
    tty: true
    working_dir: /home/developer/projects/code
