services:
  claude-code:
    build:
      context: .
      dockerfile: Dockerfile
    image: claude-code-dev
    container_name: claude-code
    volumes:
      - $HOME/.claude-docker:/home/developer/.claude
      - $HOME/.claude-docker.json:/home/developer/.claude.json
      - ${PROJECT_DIR:?PROJECT_DIR must be set}:/home/developer/projects/code
    stdin_open: true
    tty: true
    working_dir: /home/developer/projects/code
