services:
  claude-code:
    build:
      context: .
      dockerfile: Dockerfile
    image: claude-code-dev
    container_name: claude-code
    volumes:
      - $HOME/.claude:/home/developer/.claude
      - $HOME/.claude.json:/home/developer/.claude.json
      - ${PROJECT_DIR:-$HOME/Development/bug_hawk}:/home/developer/projects/code
    stdin_open: true
    tty: true
    working_dir: /home/developer/projects/code
